/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicsadministration;

import java.awt.ComponentOrientation;
import java.awt.Font;
import java.io.File;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author engmu
 */
public class DoctoresPanel extends javax.swing.JPanel {

    String addphoto = "";
    Vector idclincname = new Vector();
    int row = -1;

    /**
     * Creates new form EmployeePanel
     */
    public DoctoresPanel() {
        initComponents();
        Tools.HeaderRendererCenter(table);
        Tools.rowRenderCenter(table);
        Tools.setComponentBackGroundColor(this);
        Tools.setComponentBackGroundColor(jPanel2);
        Tools.setComponentBackGroundColor(jPanel6);
        Tools.setComponentBackGroundColor(radiomonth);
        Tools.setComponentBackGroundColor(radiopercent);
        Tools.setScrollBackGroundColor(jScrollPane1);
        Tools.setComponentBackGroundColor(combospecial);
        Tools.setComponentBackGroundColor(combosex);
        updateSpecialization();
        updateTable();
    }

    public void updateSpecialization() {
        String statement = "SELECT id, name FROM clincname ;";
        ResultSet rs = Tools.select_query(statement);
        try {
            while (rs.next()) {
                idclincname.add(rs.getString(1));
                combospecial.addItem(rs.getString(2));
            }
        } catch (Exception ex) {
        }
        Tools.closeConnection();
    }

    public String getPeriodValue() {
        String value;
        if (radiomonth.isSelected()) {
            value = "0";
        } else {
            value = "1";
        }
        return value;
    }

    public void btnAddPhoto() {
        addphoto = Tools.pathSelectFileChooser();
        if (!addphoto.isEmpty()) {
            icone.setIcon(new ImageIcon(addphoto));
        }
    }

    public void updateTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        String statement = "SELECT * FROM doctors";
        Tools.tableUpdate(model, statement, 10);
        for (int i = 0; i < table.getRowCount(); i++) {
            String period = String.valueOf(table.getValueAt(i, 8));
            if ("0".equals(period)) {
                table.setValueAt("شهري", i, 8);
            } else {
                table.setValueAt("نسبه", i, 8);
            }
            try {
                table.setValueAt(combospecial.getItemAt(idclincname.indexOf(table.getValueAt(i, 5))), i, 5);
                int index = Integer.parseInt(String.valueOf(table.getValueAt(i, 6)));
                table.setValueAt(combosex.getItemAt(index), i, 6);
            } catch (Exception ex) {
            }
        }
    }

    public void resetValue() {
        addphoto = "";
        txtcode.setText("");
        txtname.setText("");
        txtaddress.setText("");
        txtphone.setText("");
        txtemail.setText("");
        combospecial.setSelectedIndex(0);
        combosex.setSelectedIndex(0);
        txtsalary.setText("");
        radiomonth.setSelected(true);
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-image.png")));
    }

    public void filterTable(String serch) {
        try {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            table.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(serch.trim()));

        } catch (Exception ex) {
        }

    }

    public void btnSearch() {
        if (!txtsearch.getText().isEmpty()) {
            if (combochoose.getSelectedIndex() == 0) {
                int id = 0;
                try {
                    id = Integer.parseInt(txtsearch.getText().trim());
                    String statement = "SELECT * FROM doctors WHERE id = " + id + " ;";
                    DefaultTableModel model = (DefaultTableModel) table.getModel();
                    Tools.tableUpdate(model, statement, 10);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "يجب ادخال قيمه عدديه ");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "يجب ادخال قيمه في خانه البحث");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        txtcode = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        combospecial = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        combosex = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        radiomonth = new javax.swing.JRadioButton();
        radiopercent = new javax.swing.JRadioButton();
        icone = new javax.swing.JLabel();
        btnaddimage = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnsearch = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        combochoose = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        txtcode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Name");

        txtname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtname.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtname.setMaximumSize(new java.awt.Dimension(214, 40));
        txtname.setMinimumSize(new java.awt.Dimension(214, 40));
        txtname.setPreferredSize(new java.awt.Dimension(214, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Address");

        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtaddress.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Phone");

        txtphone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtphone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Gender");

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtemail.setMaximumSize(new java.awt.Dimension(214, 40));
        txtemail.setMinimumSize(new java.awt.Dimension(214, 40));
        txtemail.setPreferredSize(new java.awt.Dimension(214, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Email");

        combospecial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Major");

        combosex.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        combosex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        combosex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosexActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Salary");

        txtsalary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsalary.setText("0");
        txtsalary.setMaximumSize(new java.awt.Dimension(214, 40));
        txtsalary.setMinimumSize(new java.awt.Dimension(214, 40));
        txtsalary.setPreferredSize(new java.awt.Dimension(214, 40));

        buttonGroup1.add(radiomonth);
        radiomonth.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        radiomonth.setSelected(true);
        radiomonth.setText("Monthly");
        radiomonth.setToolTipText("الراتب الشهري");

        buttonGroup1.add(radiopercent);
        radiopercent.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        radiopercent.setText("Percentge");
        radiopercent.setToolTipText("نسبه من كل مريض");

        icone.setBackground(new java.awt.Color(255, 255, 255));
        icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-image.png"))); // NOI18N
        icone.setMaximumSize(new java.awt.Dimension(230, 150));
        icone.setMinimumSize(new java.awt.Dimension(230, 150));
        icone.setOpaque(true);
        icone.setPreferredSize(new java.awt.Dimension(230, 150));
        icone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconeMouseClicked(evt);
            }
        });

        btnaddimage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnaddimage.setText("Add Photo");
        btnaddimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddimageActionPerformed(evt);
            }
        });

        btnadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setText("Edit");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        jButton1.setToolTipText("الرجوع الى الشاشه الرئيسيهط");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnaddimage, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(combosex, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combospecial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtaddress))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15))
                                .addGap(69, 69, 69))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(radiopercent)
                                .addGap(18, 18, 18)
                                .addComponent(radiomonth)
                                .addGap(97, 97, 97)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtemail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtsalary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16)))
                        .addGap(11, 11, 11))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(icone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(btnaddimage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(combospecial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(combosex, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19)))
                                .addGap(31, 31, 31))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(radiomonth)
                                        .addComponent(radiopercent))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnupdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btndelete)))
                                .addGap(12, 12, 12)))
                        .addComponent(icone, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.getTableHeader().setFont(new Font("NewTimeRoman", Font.BOLD, 18));
        table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Address", "phone", "Email", "Major", "Gender", "Salary", "Dealing way", "Personal photo"
            }
        ));
        table.setGridColor(new java.awt.Color(0, 255, 255));
        table.setRowHeight(40);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.setToolTipText("استخدم للبحث عن موظف برقم الكود");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        combochoose.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        combochoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code", "Filter" }));
        combochoose.setToolTipText("اختيار طريقه البحث");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(combochoose, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsearch)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combochoose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        ResultSet rs = Tools.select_query("SELECT * FROM doctors; ");
        int count = 1;
        try {
            while (rs.next()) {
                count++;
            }
        } catch (Exception ex) {
        }
        if (count <= 5) {
            if (!txtname.getText().isEmpty() && combospecial.getSelectedIndex() > -1) {
                boolean cheack = false;
                if (addphoto.isEmpty()) {
                    String statement = "INSERT INTO doctors (name, address, phone, email, special, sex, salary, period) "
                            + "VALUES "
                            + "('" + txtname.getText() + "', '" + txtaddress.getText() + "', '" + txtphone.getText() + "',"
                            + " '" + txtemail.getText() + "', "
                            + "'" + idclincname.get(combospecial.getSelectedIndex()) + "', " + combosex.getSelectedIndex() + ", "
                            + " " + txtsalary.getText() + ", " + getPeriodValue() + " ) ;";
                    cheack = Tools.ExecuteStatement(statement);
                } else {
                    File file = new File(addphoto);
                    String statement = "INSERT INTO doctors (name, address, phone, email, special, sex, salary, period, "
                            + "imagename, imagefile) "
                            + "VALUES "
                            + "('" + txtname.getText() + "', '" + txtaddress.getText() + "', '" + txtphone.getText() + "',"
                            + " '" + txtemail.getText() + "', "
                            + "" + idclincname.get(combospecial.getSelectedIndex()) + ", " + combosex.getSelectedIndex() + ", "
                            + " " + txtsalary.getText() + ", " + getPeriodValue() + ", '" + file.getName() + "', ? ) ;";
                    cheack = Tools.ExecuteStatementWithPicture(statement, addphoto);
                }
                if (cheack) {
                    JOptionPane.showMessageDialog(null, "تمت الاضافه بنجاح");
                    updateTable();
                    resetValue();
                }
                Tools.closeConnection();
            } else {
                JOptionPane.showMessageDialog(null, "يجب اضافه اسم الدكتور");
            }
        }else
            JOptionPane.showMessageDialog(null, "يجب شراء النسخه الكامله لتهيئه الحد الاستيعابي للبرنامج");
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        if (!txtcode.getText().isEmpty()) {
            String statement = "DELETE FROM doctors WHERE id = " + txtcode.getText() + " ;";
            boolean cheack = Tools.ExecuteStatement(statement);
            if (cheack) {
                JOptionPane.showMessageDialog(null, "تم الحذف بنجاح");
                resetValue();
                updateTable();
            }
            Tools.closeConnection();
        } else {
            JOptionPane.showMessageDialog(null, "يجب تحديد سطر من الجدول");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        if (!txtcode.getText().isEmpty()) {
            boolean cheack = false;
            if (addphoto.isEmpty()) {
                String statement = "UPDATE doctors SET name = '" + txtname.getText() + "', address = '" + txtaddress.getText() + "', "
                        + "phone = '" + txtphone.getText() + "', email = '" + txtemail.getText() + "', "
                        + "special = " + idclincname.get(combospecial.getSelectedIndex()) + ", "
                        + "sex = " + combosex.getSelectedIndex() + ", salary = " + txtsalary.getText() + ", "
                        + "period = " + getPeriodValue() +" WHERE id = " + txtcode.getText() + " ;";
                cheack = Tools.ExecuteStatement(statement);
            } else {
                File file = new File(addphoto);
                String statement = "UPDATE doctors SET name = '" + txtname.getText() + "', address = '" + txtaddress.getText() + "', "
                        + "phone = '" + txtphone.getText() + "', email = '" + txtemail.getText() + "', "
                        + "special = " + idclincname.get(combospecial.getSelectedIndex()) + ", "
                        + "sex = " + combosex.getSelectedIndex() + ", salary = " + txtsalary.getText() + ", "
                        + "period = " + getPeriodValue() + ", "
                        + "imagename = '" + file.getName() + "', imagefile = ? WHERE id = " + txtcode.getText() + " ;";
                cheack = Tools.ExecuteStatementWithPicture(statement, addphoto);
            }
            if (cheack) {
                JOptionPane.showMessageDialog(null, "تم التعديل بنجاح");
                resetValue();
                updateTable();
            }
            Tools.closeConnection();
        } else {
            JOptionPane.showMessageDialog(null, "يجب تحديد سطر من الجدول");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        this.row = row;
        txtcode.setText(String.valueOf(table.getValueAt(row, 0)));
        txtname.setText(String.valueOf(table.getValueAt(row, 1)));
        txtaddress.setText(String.valueOf(table.getValueAt(row, 2)));
        txtphone.setText(String.valueOf(table.getValueAt(row, 3)));
        txtemail.setText(String.valueOf(table.getValueAt(row, 4)));
        combospecial.setSelectedItem(String.valueOf(table.getValueAt(row, 5)));
        combosex.setSelectedItem(String.valueOf(table.getValueAt(row, 6)));
        txtsalary.setText(String.valueOf(table.getValueAt(row, 7)));
        if (String.valueOf(table.getValueAt(row, 8)).equals("0")) {
            radiomonth.setSelected(true);
        } else {
            radiopercent.setSelected(true);
        }
        ImageIcon icon = Tools.getImageIcon("SELECT imagefile FROM doctors WHERE id = " + txtcode.getText() + " ;");
        if (icon != null) {
            icone.setIcon(icon);
        } else {
            icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/no-image.png")));
        }
        Tools.closeConnection();
        if (table.getSelectedColumn() == 9 && !String.valueOf(table.getValueAt(row, 9)).isEmpty() && 
                !String.valueOf(table.getValueAt(row, 9)).equals("null")) {
            String statement = "SELECT imagefile FROM doctors WHERE id = " + table.getValueAt(row, 0) + " ;";
            new ImageZoom(null, true, statement, String.valueOf(table.getValueAt(row, 9))).setVisible(true);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        if (evt.getSource() == txtsearch) {
            if (combochoose.getSelectedIndex() == 1) {
                try {
                    filterTable(String.valueOf(txtsearch.getText()));
                } catch (Exception ex) {
                }
            }
            if (txtsearch.getText().isEmpty()) {
                updateTable();
            }
        }
        if (evt.getKeyCode() == 10) {
            btnSearch();
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        btnSearch();
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tools.setImagePanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void combosexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combosexActionPerformed

    private void btnaddimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddimageActionPerformed
        // TODO add your handling code here:
        btnAddPhoto();
    }//GEN-LAST:event_btnaddimageActionPerformed

    private void iconeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconeMouseClicked
        // TODO add your handling code here:
        if (!txtcode.getText().isEmpty()) {
            String statement = "SELECT imagefile FROM doctors WHERE id = " + txtcode.getText() + " ;";
            new ImageZoom(null, true, statement, String.valueOf(table.getValueAt(row, 9))).setVisible(true);
        }
    }//GEN-LAST:event_iconeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddimage;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combochoose;
    private javax.swing.JComboBox<String> combosex;
    private javax.swing.JComboBox<String> combospecial;
    private javax.swing.JLabel icone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiomonth;
    private javax.swing.JRadioButton radiopercent;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JLabel txtcode;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsalary;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
