/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicsadministration;

import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author engmu
 */
public class ImagePanel extends javax.swing.JPanel {

    String path = "images\\";

    /**
     * Creates new form ImagePanel
     */
    public ImagePanel() {
        initComponents();
        Tools.setComponentBackGroundColor(image);
        setImage();
    }

    public void setImage() {
        String statement = "SELECT value FROM settings WHERE id = 8 ;";
        String name = "";
        try {
            ResultSet rs = Tools.select_query(statement);
            while (rs.next()) {
                name = rs.getString(1);
            }
            if (!name.isEmpty()) {
                image.setIcon(new ImageIcon(path + name));
            }
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();

        image.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    // End of variables declaration//GEN-END:variables
}
