/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicsadministration;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author engmu
 */
public class InformationPatientAndClientPanel extends javax.swing.JPanel {

    /**
     * Creates new form InformationPatientAndClientPanel
     */
    public InformationPatientAndClientPanel() {
        initComponents();
        Tools.HeaderRendererCenter(table);
        updateTable();
        Tools.setComponentBackGroundColor(this);
        Tools.setScrollBackGroundColor(jScrollPane1);
    }

    public void updateTable() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/delete.png"));
        Object[][] arr = new Object[5][5];
        String statement = "SELECT id, name FROM patient ;";
        ResultSet rs = Tools.select_query(statement);
        try {
            int rowcount = 0, j = 0;
            while (rs.next()) {
                rowcount++;
            }
            arr = new Object[rowcount][5];
            rs = Tools.select_query(statement);
            while (rs.next()) {
                for (int i = 0; i < 2; i++) {
                    arr[j][i] = rs.getString(i + 1);
                }
                arr[j][2] = "....";
                arr[j][3] = "....";
                arr[j][4] = icon;
                j++;
            }
            Tools.closeConnection();
        } catch (Exception ex) {
        }
        Tools.closeConnection();
        DefaultTableModel model = new DefaultTableModel(arr,
                new String[]{
                    "رقم", "الاسم", "المعلومات الشخصيه", "الكشف والخدمات", "حذف"
                }) {
            @Override
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                        return Object.class;
                    case 4:
                        return ImageIcon.class;
                    default:
                        return Object.class;
                }
            }
        };
        table.setModel(model);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < table.getColumnCount() - 1; i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    public void filterTable(String serch) {
        serch = serch.replace('\\', ' ');
        serch = serch.replace('/', ' ');
        serch = serch.replace('*', ' ');
        serch = serch.replace('-', ' ');
        serch = serch.replace('+', ' ');
        serch = serch.replace('=', ' ');
        serch = serch.replace('&', ' ');
        serch = serch.replace('^', ' ');
        serch = serch.replace('%', ' ');
        serch = serch.replace('$', ' ');
        serch = serch.replace('#', ' ');
        serch = serch.replace('@', ' ');
        serch = serch.replace('!', ' ');
        serch = serch.replace('<', ' ');
        serch = serch.replace('>', ' ');
        try {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            table.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(serch.trim()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "خطأ لا يمكن ادخل الرموز");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.getTableHeader().setFont(new Font("NewTimeRoman", Font.BOLD, 18));
        table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Personal info", "Services ", "Delete"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(0, 255, 255));
        table.setRowHeight(40);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(204, 204, 204));
        txtsearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsearch.setText("Filter");
        txtsearch.setToolTipText("اكتب هنا لفلتره الجدول");
        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearchFocusGained(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/previous.png"))); // NOI18N
        jButton1.setToolTipText("الرجوع الى الشاشه الرئيسيه");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(20, 20, 20)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        if (table.getSelectedColumn() == 2) {
            new PersonInformationPatient(String.valueOf(table.getValueAt(table.getSelectedRow(), 0))).setVisible(true);
        } else if (table.getSelectedColumn() == 3) {
            new PatientCliencServicInformation(String.valueOf(table.getValueAt(table.getSelectedRow(), 0))).setVisible(true);
        } else if (table.getSelectedColumn() == 4) {
            int ok = JOptionPane.showConfirmDialog(null, "هل تريد الحذف ؟", "اختيار", JOptionPane.YES_NO_OPTION);
            if (ok == 0) {
                boolean cheack = false;
                String statement = "DELETE FROM patientaccounts WHERE id = " + table.getValueAt(table.getSelectedRow(), 0) + " ;";
                cheack = Tools.ExecuteStatement(statement);
                statement = "DELETE FROM patientservice WHERE id = " + table.getValueAt(table.getSelectedRow(), 0) + " ;";
                cheack = Tools.ExecuteStatement(statement);
                statement = "DELETE FROM patientclinic WHERE id = " + table.getValueAt(table.getSelectedRow(), 0) + " ;";
                cheack = Tools.ExecuteStatement(statement);
                statement = "DELETE FROM patient WHERE id = " + table.getValueAt(table.getSelectedRow(), 0) + " ;";
                cheack = Tools.ExecuteStatement(statement);
                if (cheack) {
                    JOptionPane.showMessageDialog(null, "تم الحذف بنجاح");
                    updateTable();
                }
                Tools.closeConnection();
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        String txt = "";
        txt += String.valueOf(txtsearch.getText());
        filterTable(txt);
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusGained
        // TODO add your handling code here:
        txtsearch.setText("");
        txtsearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtsearchFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Tools.setImagePanel();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
