/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicsadministration;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Font;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author engmu
 */
public class PatientNextPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientNextPanel
     */
    public PatientNextPanel() {
        initComponents();
        Tools.HeaderRendererCenter(table);
        tableUpdate();
        Tools.setComponentBackGroundColor(this);
        Tools.setScrollBackGroundColor(jScrollPane1);
    }

    private void tableUpdate() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/delete.png"));
        Object[][] arr = new Object[5][5];
        String statement = "SELECT * FROM next ;";
        ResultSet rs = Tools.select_query(statement);
        try {
            int rowcount = 0, j = 0;
            while (rs.next()) {
                rowcount++;
            }
            arr = new Object[rowcount][7];
            rs = Tools.select_query(statement);
            while (rs.next()) {
                for (int i = 0; i < 6; i++) {
                    arr[j][i] = rs.getString(i + 1);
                }
                arr[j][6] = icon;
                j++;
            }
            Tools.closeConnection();
        } catch (Exception ex) {
        }
        Tools.closeConnection();
        DefaultTableModel model = new DefaultTableModel(arr,
                new String[]{
                    "رقم الدور", "الاسم", "العياده", "الطبيب المعالج", "التاريخ", "الوقت", "حذف"
                }) {
            @Override
            public Class<?> getColumnClass(int column) {
                switch (column) {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                    case 4:
                    case 5:
                        return Object.class;
                    case 6:
                        return ImageIcon.class;
                    default:
                        return Object.class;
                }
            }
        };
        table.setModel(model);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i < table.getColumnCount() - 1; i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    public void filterTable(String serch) {
        serch = serch.replace('\\', ' ');
        serch = serch.replace('/', ' ');
        serch = serch.replace('*', ' ');
        serch = serch.replace('-', ' ');
        serch = serch.replace('+', ' ');
        serch = serch.replace('=', ' ');
        serch = serch.replace('&', ' ');
        serch = serch.replace('^', ' ');
        serch = serch.replace('%', ' ');
        serch = serch.replace('$', ' ');
        serch = serch.replace('#', ' ');
        serch = serch.replace('@', ' ');
        serch = serch.replace('!', ' ');
        serch = serch.replace('<', ' ');
        serch = serch.replace('>', ' ');
        try {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            table.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(serch.trim()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "خطأ لا يمكن ادخل الرموز");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.getTableHeader().setFont(new Font("NewTimeRoman", Font.BOLD, 18));
        table.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Turn ", "Name", "Clinic", "Doctor", "Date", "Time", "Delete"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setGridColor(new java.awt.Color(0, 255, 255));
        table.setRowHeight(40);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsearch.setForeground(new java.awt.Color(153, 153, 153));
        txtsearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtsearch.setText("Filter");
        txtsearch.setToolTipText("اكتب هنا لفلتره الجدول");
        txtsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsearchFocusGained(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if (row > -1 && table.getSelectedColumn() == 6) {
            int ok = JOptionPane.showConfirmDialog(null, "هل تريد الحذف بالتأكيد ؟", "اختيار", JOptionPane.YES_NO_OPTION);
            if (ok == 0) {
                String statement = "DELETE FROM next WHERE id = " + table.getValueAt(row, 0) + " ;";
                boolean check = Tools.ExecuteStatement(statement);
                if (check) {
                    JOptionPane.showMessageDialog(null, "تم الحذف بنجاح");
                }
                Tools.closeConnection();
                tableUpdate();
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void txtsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsearchFocusGained
        // TODO add your handling code here:
        txtsearch.setText("");
        txtsearch.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtsearchFocusGained

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        String txt = "";
        txt += String.valueOf(txtsearch.getText());
        filterTable(txt);
    }//GEN-LAST:event_txtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

}
